### PR TITLE
Send server logs to rcon client.

### PR DESCRIPTION
**Pull request by ErikPDev**
This sends server Logs to the rcon client.

### CODE REVIEW

**Comment by dktapps** [comment]
RCON isn't supposed to be used this way. Besides, one of the appeals to RCON is that you _don't_ get spammed with log messages while trying to actually use commands.

**Comment by ErikPDev** [comment]
> RCON isn't supposed to be used this way. Besides, one of the appeals to RCON is that you _don't_ get spammed with log messages while trying to actually use commands.

Thought it would be a nice touch lol, and I believe there is a packet type that indicates a response, therefore the rcon won't get spammed with log messages when using the command xd

**Comment by dktapps** [comment]
There's also security issues to consider.

**Comment by dktapps** [comment]
Overall RCON is generally a shitty way to control a server due to the lack of ability to tell the difference between different users. The password is sent over the wire in plaintext and there's no way to give different permissions to different users. This is why it's not part of the core anymore.

The plugin is provided for people who need it for legacy workflows, but it shouldn't be used by new users.

**Pull request closed without merging**
